Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'restaurants#index'

  get '/restaurants' => 'restaurants#index'
  get '/restaurants/new' => 'restaurants#new'
  post '/restaurants' => 'restaurants#create'
  get '/restaurants/:id' => 'restaurants#show'
  get '/restaurants/:id/edit' => 'restaurants#edit'
  get '/restaurants/:id/show_reservations' => 'restaurants#show_reservations'
  patch '/restaurants/:id' => 'restaurants#update'
  delete '/restaurants/:id' => 'restaurants#destroy'
  get '/reservations' => 'reservations#index'
  get '/reservations/canceled' => 'reservations#canceled'
  get '/reservations/show_all' => 'reservations#show_all'
  get '/reservations/:id/new_review' => 'reservations#new_review'
  post '/reservations/:id/new_review' => 'reservations#create_review'
  delete '/reservations/:id' => 'reservations#destroy'
  post '/reservations' => 'reservations#create'
  get '/users/new' => 'users#new'
  get '/users' => 'users#index'
  get '/users/edit' => 'users#edit'
  patch '/users' => 'users#update'
  post '/users' => 'users#create'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  get '/stats' => 'admins#stats'
end
